# Generated by Django 2.1.7 on 2019-03-12 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfHD', models.IntegerField(blank=True, null=True)),
                ('startTime', models.DateTimeField(default='')),
                ('predictTime', models.DateTimeField(default='')),
                ('filePath', models.CharField(default='', max_length=250)),
                ('describe', models.TextField(default='')),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('createTime',),
            },
        ),
        migrations.CreateModel(
            name='SHistoryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hd_startTime', models.DateTimeField(default='')),
                ('hd_endTime', models.DateTimeField(default='')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('filePath', models.CharField(default='', max_length=250)),
                ('describe', models.TextField(default='')),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('createTime',),
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=100)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('describe', models.TextField(default='')),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('createTime',),
            },
        ),
        migrations.CreateModel(
            name='TechIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('shortName', models.CharField(default='', max_length=100)),
                ('tType', models.CharField(default='均线型', max_length=100)),
                ('interface', models.CharField(default='', max_length=100)),
                ('parameter1', models.CharField(default='', max_length=100)),
                ('parameter2', models.CharField(default='', max_length=100)),
                ('parameter3', models.CharField(default='', max_length=100)),
                ('parameter4', models.CharField(default='', max_length=100)),
                ('parameter5', models.CharField(default='', max_length=100)),
                ('describe', models.TextField(default='')),
                ('KY1', models.CharField(default='', max_length=100)),
                ('KY2', models.CharField(default='', max_length=100)),
                ('KY3', models.CharField(default='', max_length=100)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('createTime',),
            },
        ),
        migrations.CreateModel(
            name='TIData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('filePath', models.CharField(default='', max_length=250)),
                ('describe', models.TextField(default='')),
                ('KY1', models.CharField(default='', max_length=100)),
                ('KY2', models.CharField(default='', max_length=100)),
                ('KY3', models.CharField(default='', max_length=100)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('isDelete', models.BooleanField(default=False)),
                ('TI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockDataVisualized.TechIndicator')),
                ('stockData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockDataVisualized.SHistoryData')),
            ],
            options={
                'ordering': ('createTime',),
            },
        ),
        migrations.AddField(
            model_name='shistorydata',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockDataVisualized.Stock'),
        ),
        migrations.AddField(
            model_name='predictdata',
            name='SHD',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockDataVisualized.SHistoryData'),
        ),
    ]
